"""Commit

Revision ID: f9b0f63fb183
Revises: 57e3d9cc19d5
Create Date: 2023-01-25 12:10:05.082537

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9b0f63fb183'
down_revision = '57e3d9cc19d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_of_car', sa.String(length=100), nullable=False),
    sa.Column('driver', sa.String(length=100), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('num_of_phone', sa.String(length=100), nullable=False),
    sa.Column('sms_code', sa.String(length=100), nullable=False),
    sa.Column('time', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('num_of_car', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('driver', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('client', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('destination', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('num_of_phone', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('sms_code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('time', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
